### PR TITLE
[IOS-5416]Remove i386 architecture error for GoogleMobileAdsMediationVungle podspec

### PR DESCRIPTION
**Pull request by YueVungle**
This PR is removing i386 architecture error for GoogleMobileAdsMediationVungle.podspec when doing validation. And also update the VungleAdMobAdapter framework based on the latest VungleAdsSDK.

IOS-5416

### CODE REVIEW

**Comment by stanley-vungle** [comment]
@YueVungle When I try to validate the podspec, I get the error "Could not find or use auto-linked framework 'VungleAdsSDK'". How did you get around this issue?

The command that I run is from the ticket:
pod spec lint GoogleMobileAdsMediationVungle.podspec --sources=https://github.com/CocoaPods/Specs.git,https://github.com/Vungle/ios-sdk-beta.git

**Comment by YueVungle** [comment]
> @YueVungle When I try to validate the podspec, I get the error "Could not find or use auto-linked framework 'VungleAdsSDK'". How did you get around this issue?
> 
> The command that I run is from the ticket: pod spec lint GoogleMobileAdsMediationVungle.podspec --sources=https://github.com/CocoaPods/Specs.git,https://github.com/Vungle/ios-sdk-beta.git


@stanley-vungle Could you please run blew command to clean the cache？
` pod cache clean --all`

Then do the validation again. Thanks a lot. :)

**Comment by YueVungle** [comment]
Please run below commands to do the validations:
```
pod lib lint GoogleMobileAdsMediationVungle.podspec	 --verbose --no-clean  --sources=https://github.com/CocoaPods/Specs.git,https://github.com/Vungle/ios-sdk-beta.git
pod spec lint GoogleMobileAdsMediationVungle.podspec --verbose --no-clean  --sources=https://github.com/CocoaPods/Specs.git,https://github.com/Vungle/ios-sdk-beta.git
```
Thanks a lot. :)

**Review by shiv-vungle — APPROVED** [review]
LGTM

**Review by ManojBudumuru-vungle — APPROVED** [review]

**Review by johnmaivungle — APPROVED** [review]

**Pull request merged**
